### ISSUE TITLE
如何创建出虚拟网卡和正常使用库

### ISSUE THREAD

**Issue by fun0gs** [gonewind73/pytuntap#1]
你好，我想用OpenVPN的tap驱动实现一个简单的VPN用于研究学习，在PyPI搜到了你的代码库，安装后却无法正常使用，config方法提示netsh报错如下(原因大致是因为没有提前创建出网卡?)：
`subprocess.CalledProcessError: Command 'netsh interface ip set address name="None" source=static addr=192.168.3.2 mask=255.255.255.0 gateway=192.168.3.1' returned non-zero exit status 1.`

因为对windows编程不太熟悉看了源码也没法深入debug，因此烦请您帮忙，谢谢:)

PS: 驱动安装了的，各种vpn软件都给创建了3个tap网卡出来了。
代码如下：
```python3
from tuntap import TunTap
tap = TunTap(nic_type="Tap",nic_name="tap0")
#tap.create()
tap.config(ip="192.168.3.2",mask="255.255.255.0",gateway="192.168.3.1")
```

**Comment by fun0gs** [comment]
是需要自己先创建出网卡然后给程序用吗，我先自己研究着看

**Comment by Unixeno** [comment]
权限不够，用管理员权限运行
